# Generated by Django 4.2.15 on 2024-12-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_rename_is_approved_review_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(to='fitness.product'),
        ),
    ]
