# Generated by Django 4.2.15 on 2024-11-08 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_remove_wishlist_product_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together=set(),
        ),
    ]
