# Generated by Django 4.2.15 on 2024-12-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_newslettersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='pause_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='pause_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
