# Generated by Django 4.2.15 on 2024-12-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_subscriptionplan_pause_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='resume_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='resume_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pause_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pause_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume_requested',
            field=models.BooleanField(default=False),
        ),
    ]
