# Generated by Django 4.2.15 on 2024-12-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_subscriptionplan_resume_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
