# Generated by Django 4.2.15 on 2024-11-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0009_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_spotlight',
            field=models.BooleanField(default=False),
        ),
    ]
