# Generated by Django 4.2.15 on 2024-11-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0010_product_is_spotlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_spotlight',
            field=models.BooleanField(default=False),
        ),
    ]
