# Generated by Django 4.2.15 on 2024-11-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0012_remove_subscriptionplan_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_spotlight',
            field=models.BooleanField(default=False),
        ),
    ]
