# Generated by Django 4.2.15 on 2025-02-27 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0018_remove_order_status_alter_order_order_date_and_more'),
        ('cart', '0010_order_product_alter_cart_user_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='final_total',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
